### ISSUE TITLE
[NOTES] Experiences with dbt-synthea for Big Patient Datasets

### ISSUE THREAD

**Issue by TheCedarPrince** [OHDSI/dbt-synthea#91]
Hey @katy-sadowski,

I ended up opening an issue as Discussions is not enabled for this repo.

Wanted to share some notes on my experiences with you on using this solution for 1 million patients each with 5 year retrospective look back:

- The Python solution worked fine although I noticed two things:
    - I opened a PR to specify the suggested Python version https://github.com/OHDSI/dbt-synthea/pull/87
    - Ran into an issue about `cffi` being needed -- might be missing from dependencies somehow https://github.com/OHDSI/dbt-synthea/issues/88
    - Worked fine with miniconda which was nice!
- I felt like the instructions about where the `.dbt` file should go was a little vague
    - Opened a docs PR to maybe help with that: https://github.com/OHDSI/dbt-synthea/pull/89
- Strange errors occur with loading vocabularies:
    - Made a note of it here: https://github.com/OHDSI/dbt-synthea/issues/90
- Loading this data in the step `dbt run` fails on large tables in the OMOP Schema -- especially those tables which have a large lineage. 

I am going to reproduce these errors tomorrow and actually generate 1 million patients from scratch using Synthea and re-run the pipeline to find all the tables that fail to be built. 

Hope this helps folks!

~ tcp :deciduous_tree:

**Comment by katy-sadowski** [comment]
Fantastic, thanks @TheCedarPrince !  I think I'll try it on my end as well so we have 2x OS & laptop worth of data on performance :)

**Comment by lawrenceadams** [comment]
Nice work @TheCedarPrince ! I was playing around with this in Snowflake over the weekend and generated a million patients and started running it on their to see how it would benchmark compared to duckdb - keen to hear how you get on!

**Comment by TheCedarPrince** [comment]
Question for folks:

Can I run dbt-synthea on "chunks" of data I have manually split up (Meaning, I have folders like `csvs_1`, `csvs_2`, etc. and for each folder, have about 200K patients)? And then run dbt-synthea against each of these folders without rebuilding the prior DuckDB database? Was wondering as then I can chunk out the ETL simply this way.

**Comment by TheCedarPrince** [comment]
Also, @katy-sadowski , I was going to tinker a little later with also getting [hyperfine](https://github.com/sharkdp/hyperfine) to work with this process for benchmarking purposes. It's considered the state of the art for benchmarking and is used a ton in numerical or HPC environments -- especially like high energy physics areas. Ran into some problems yesterday when I tried to naively run it so there might be some system environment quirks.

**Comment by lawrenceadams** [comment]
> Can I run dbt-synthea on "chunks" of data I have manually split up (Meaning, I have folders like `csvs_1`, `csvs_2`, etc. and for each folder, have about 200K patients)? And then run dbt-synthea against each of these folders without rebuilding the prior DuckDB database? Was wondering as then I can chunk out the ETL simply this way.

Yeah you definitely can with duckdb with next to any effort - you'd have to change the sources to [glob like this](https://duckdb.org/docs/data/multiple_files/overview.html)!

**Comment by TheCedarPrince** [comment]
Interesting -- what files would need to be changed to accommodate this in `dbt-synthea`? Because I can load vocab now fine in #90 and mostly the loading of data is fine, but the problem I have, as mentioned:

> [ETLing] this data in the step dbt run fails on large tables in the OMOP Schema -- especially those tables which have a large lineage.

So I would want to `dbt run` multiple times versus loading. Or do you see the load step as helping with the ETL step @lawrenceadams ?

**Comment by lawrenceadams** [comment]
So there are two approaches:
   1. we could either modify the loader script to glob files , or...
   2. more simply - given duckdb doesn't need files loaded before it can use them (@katy-sadowski might correct me - but my understanding as to why we have a step where we actively load files into the pipeline is to keep the source/ref files identical between database systems e.g. Postgres/Duckdb/etc can use the same code), you could modify a `sources.yml` file to incorporate something like the below:

<img width="1010" alt="image" src="https://github.com/user-attachments/assets/952eab44-296f-43eb-9f23-ee6fa596e484">

I would modify the sources file below

https://github.com/OHDSI/dbt-synthea/blob/4c34141f301ad30601bd7c373bab3912da2c26f6/models/staging/synthea/_synthea__sources.yml#L1-L24

to:

```yml
version: 2

sources:
  - name: synthea
    meta:
      external_location: "/path/to/synthea/output/{name}/*.csv"
    tables:
      - name: allergies
      - name: careplans
      - name: claims_transactions
      - name: claims
      - name: conditions
      - name: devices
      - name: encounters
      - name: imaging_studies
      - name: immunizations
      - name: medications
      - name: observations
      - name: organizations
      - name: patients
      - name: payer_transitions
      - name: payers
      - name: procedures
      - name: providers
      - name: supplies 
```

and it should work without having to have an explicity _load_ step 🚀 

Does that make sense? It blew my mind the first time I realised I could do this! Makes working with partitioned CSV/Parquet files so much easier 😄
